### ISSUE TITLE
Update changelog toaster for PATCH

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/dim-release-bot#1]
If we execute a patch we should consider prepending the new release notes to the changelog toaster

Ex:

<img width="505" alt="screen shot 2017-09-29 at 12 43 19 pm" src="https://user-images.githubusercontent.com/424158/31033271-3a93d08c-a514-11e7-85cb-fc9f7b9a2e9e.png">
<img width="837" alt="screen shot 2017-09-29 at 12 43 25 pm" src="https://user-images.githubusercontent.com/424158/31033272-3a95c1a8-a514-11e7-898f-5915ca84befc.png">

**Comment by bhollis** [comment]
This is a good idea
